"""Pytest configuration and shared fixtures for Academic RAG System."""

import pytest
from pathlib import Path
import json
import tempfile
import shutil
from typing import Dict, Any, List
from unittest.mock import MagicMock, Mock

# Add project root to path
import sys
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))


# ============================================================================
# Session-scoped fixtures (expensive, run once)
# ============================================================================

@pytest.fixture(scope="session")
def project_root_path() -> Path:
    """Return project root directory."""
    return Path(__file__).parent.parent


@pytest.fixture(scope="session")
def test_data_dir(project_root_path) -> Path:
    """Return test fixtures directory."""
    return project_root_path / "tests" / "fixtures"


@pytest.fixture(scope="session")
def sample_papers(test_data_dir) -> List[Dict[str, Any]]:
    """Load sample papers for testing."""
    sample_file = test_data_dir / "sample_papers.json"
    if not sample_file.exists():
        # Return minimal sample if file doesn't exist
        return [
            {
                "title": "Attention Is All You Need",
                "authors": ["Vaswani et al."],
                "year": 2017,
                "abstract": "The dominant sequence transduction models...",
                "sections": [
                    {
                        "section_type": "abstract",
                        "content": "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks."
                    },
                    {
                        "section_type": "introduction",
                        "content": "Recurrent neural networks, long short-term memory and gated recurrent neural networks have been firmly established as state of the art approaches."
                    }
                ]
            }
        ]

    with open(sample_file, 'r', encoding='utf-8') as f:
        return json.load(f)


@pytest.fixture(scope="session")
def sample_queries() -> List[str]:
    """Sample queries for testing retrieval."""
    return [
        "What is the transformer architecture?",
        "How does attention mechanism work?",
        "What are the advantages of self-attention?",
        "Explain positional encoding in transformers",
        "What is multi-head attention?"
    ]


# ============================================================================
# Function-scoped fixtures (run for each test)
# ============================================================================

@pytest.fixture
def temp_dir():
    """Create temporary directory for tests."""
    tmp = tempfile.mkdtemp()
    yield Path(tmp)
    shutil.rmtree(tmp, ignore_errors=True)


@pytest.fixture
def mock_config():
    """Mock configuration for testing."""
    from configs.config_loader import Config, EmbeddingConfig, RetrievalConfig, ChunkingConfig, GenerationConfig

    config = Config()
    # Override with test-specific values
    config.embedding.device = "cpu"
    config.embedding.batch_size = 4
    config.retrieval.top_k = 3
    config.chunking.chunk_size = 200
    config.generation.timeout = 10

    return config


@pytest.fixture
def mock_embedding_model():
    """Mock embedding model for testing."""
    mock = MagicMock()
    mock.encode.return_value = [[0.1] * 768]  # 768-dim vector
    mock.get_sentence_embedding_dimension.return_value = 768
    return mock


@pytest.fixture
def mock_llm_client():
    """Mock LLM client for testing."""
    mock = MagicMock()
    mock.generate.return_value = {
        'response': 'This is a test answer generated by the mock LLM.',
        'model': 'mock-model',
        'created_at': '2024-01-15T10:00:00Z'
    }
    mock.is_available.return_value = True
    return mock


@pytest.fixture
def sample_text():
    """Sample text for chunking tests."""
    return """
    # Introduction

    This is a test document with multiple sections. It contains various types of content
    including paragraphs, lists, and code blocks.

    ## Background

    Deep learning has revolutionized the field of artificial intelligence. Recent advances
    in transformer architectures have enabled significant progress in natural language
    processing tasks.

    ## Method

    Our approach consists of three main components:
    1. Data preprocessing
    2. Model training
    3. Evaluation

    The model architecture is based on the transformer encoder-decoder framework.

    ## Results

    We achieved state-of-the-art performance on multiple benchmarks.

    | Dataset | Accuracy | F1 Score |
    |---------|----------|----------|
    | Test1   | 0.95     | 0.94     |
    | Test2   | 0.92     | 0.91     |

    ## Conclusion

    Our experiments demonstrate the effectiveness of the proposed approach.
    """


@pytest.fixture
def sample_chunks():
    """Sample chunks for retrieval tests."""
    return [
        {
            "text": "The transformer architecture uses self-attention mechanisms to process sequences.",
            "metadata": {
                "source": "paper1.pdf",
                "page": 3,
                "section": "introduction"
            }
        },
        {
            "text": "Multi-head attention allows the model to jointly attend to information from different representation subspaces.",
            "metadata": {
                "source": "paper1.pdf",
                "page": 5,
                "section": "method"
            }
        },
        {
            "text": "Positional encodings are added to give the model information about token positions.",
            "metadata": {
                "source": "paper1.pdf",
                "page": 6,
                "section": "method"
            }
        }
    ]


# ============================================================================
# Skip markers
# ============================================================================

def pytest_configure(config):
    """Configure custom markers."""
    config.addinivalue_line("markers", "slow: marks tests as slow")
    config.addinivalue_line("markers", "integration: marks integration tests")
    config.addinivalue_line("markers", "regression: marks regression tests")
    config.addinivalue_line("markers", "requires_ollama: requires Ollama running")
    config.addinivalue_line("markers", "requires_gpu: requires GPU")


@pytest.fixture
def skip_if_no_ollama():
    """Skip test if Ollama is not running."""
    import requests
    try:
        response = requests.get("http://localhost:11434/api/version", timeout=2)
        if response.status_code != 200:
            pytest.skip("Ollama not running")
    except:
        pytest.skip("Ollama not available")


@pytest.fixture
def skip_if_no_gpu():
    """Skip test if GPU is not available."""
    import torch
    if not torch.cuda.is_available() and not torch.backends.mps.is_available():
        pytest.skip("GPU not available")


# ============================================================================
# Utility fixtures
# ============================================================================

@pytest.fixture
def mock_vector_store():
    """Mock vector store for testing."""
    mock = MagicMock()
    mock.add_texts.return_value = ["id1", "id2", "id3"]
    mock.similarity_search.return_value = [
        {
            "id": "id1",
            "text": "Sample chunk 1",
            "score": 0.95,
            "metadata": {"source": "paper1.pdf"}
        },
        {
            "id": "id2",
            "text": "Sample chunk 2",
            "score": 0.85,
            "metadata": {"source": "paper2.pdf"}
        }
    ]
    mock.get_size.return_value = 1000
    return mock


@pytest.fixture
def baseline_metrics():
    """Baseline metrics for regression testing."""
    return {
        "retrieval": {
            "precision@5": 0.85,
            "recall@5": 0.72,
            "mrr": 0.78,
            "ndcg@5": 0.81
        },
        "generation": {
            "faithfulness": 0.88,
            "relevance": 0.91,
            "answer_length_avg": 245,
            "latency_ms": 1500
        }
    }


@pytest.fixture(autouse=True)
def reset_singletons():
    """Reset singleton instances between tests."""
    # Add any singleton reset logic here
    yield
    # Cleanup after test


# ============================================================================
# Test data creation helpers
# ============================================================================

@pytest.fixture
def create_test_paper():
    """Factory fixture for creating test paper data."""
    def _create_paper(
        title: str = "Test Paper",
        abstract: str = "Test abstract",
        num_sections: int = 3
    ) -> Dict[str, Any]:
        return {
            "title": title,
            "authors": ["Test Author"],
            "year": 2024,
            "abstract": abstract,
            "sections": [
                {
                    "section_type": f"section_{i}",
                    "content": f"Content for section {i}"
                }
                for i in range(num_sections)
            ]
        }
    return _create_paper


@pytest.fixture
def create_test_chunk():
    """Factory fixture for creating test chunk data."""
    def _create_chunk(
        text: str = "Test chunk text",
        metadata: Dict[str, Any] = None
    ):
        return {
            "text": text,
            "metadata": metadata or {
                "source": "test.pdf",
                "page": 1,
                "section": "test"
            }
        }
    return _create_chunk


# ============================================================================
# Performance tracking
# ============================================================================

@pytest.fixture(autouse=True)
def track_test_performance(request):
    """Track test execution time."""
    import time
    start = time.time()
    yield
    duration = time.time() - start
    if duration > 1.0:  # Warn if test takes more than 1 second
        print(f"\n⚠️  Slow test: {request.node.name} took {duration:.2f}s")
