# M3 Max优化配置
system:
  device: "mps"
  max_memory_gb: 32
  batch_size: 64

models:
  embedding_model: "all-mpnet-base-v2"
  local_llm:
    provider: "ollama"
    model: "llama3.1:8b"
    temperature: 0.3

data_sources:
  arxiv:
    categories: ["cs.AI", "cs.LG", "cs.CV", "cs.CL"]
    max_papers: 100

vector_db:
  provider: "chromadb"
  persist_directory: "vector_db"
  collection_name: "ai_papers"

retrieval:
  top_k: 5
  chunk_size: 1000
